// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: add_item_trans.sql

package database

import (
	"context"
)

const addItemTrans = `-- name: AddItemTrans :many
INSERT INTO transaction_items (item_id, transaction_id, quantity, price) 
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING item_id, transaction_id, quantity, price
`

type AddItemTransParams struct {
	ItemID        int32
	TransactionID int32
	Quantity      int32
	Price         float64
}

func (q *Queries) AddItemTrans(ctx context.Context, arg AddItemTransParams) ([]TransactionItem, error) {
	rows, err := q.db.QueryContext(ctx, addItemTrans,
		arg.ItemID,
		arg.TransactionID,
		arg.Quantity,
		arg.Price,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionItem
	for rows.Next() {
		var i TransactionItem
		if err := rows.Scan(
			&i.ItemID,
			&i.TransactionID,
			&i.Quantity,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
