// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_item.sql

package database

import (
	"context"
	"database/sql"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (upc, created_at, updated_at, item_name, item_desc, item_retail, item_cost, item_picture)
VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING upc, created_at, updated_at, item_name, item_desc, item_retail, item_cost, item_picture, item_id
`

type CreateItemParams struct {
	Upc         string
	ItemName    string
	ItemDesc    sql.NullString
	ItemRetail  float64
	ItemCost    float64
	ItemPicture sql.NullString
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.Upc,
		arg.ItemName,
		arg.ItemDesc,
		arg.ItemRetail,
		arg.ItemCost,
		arg.ItemPicture,
	)
	var i Item
	err := row.Scan(
		&i.Upc,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ItemName,
		&i.ItemDesc,
		&i.ItemRetail,
		&i.ItemCost,
		&i.ItemPicture,
		&i.ItemID,
	)
	return i, err
}
