// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_user.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, access_level, first_name, last_name, password_hash, user_name, active)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, access_level, first_name, last_name, password_hash, active, user_name
`

type CreateUserParams struct {
	AccessLevel  int32
	FirstName    string
	LastName     string
	PasswordHash string
	UserName     string
	Active       bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.AccessLevel,
		arg.FirstName,
		arg.LastName,
		arg.PasswordHash,
		arg.UserName,
		arg.Active,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccessLevel,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.Active,
		&i.UserName,
	)
	return i, err
}
