// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_trans.sql

package database

import (
	"context"
)

const createTrans = `-- name: CreateTrans :one
INSERT INTO transactions (customer_id, transaction_date)
VALUES (
    $1,
    NOW()
)
RETURNING transaction_id, customer_id, transaction_date
`

func (q *Queries) CreateTrans(ctx context.Context, customerID int32) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTrans, customerID)
	var i Transaction
	err := row.Scan(&i.TransactionID, &i.CustomerID, &i.TransactionDate)
	return i, err
}
