// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_transactions.sql

package database

import (
	"context"
	"time"
)

const getTransactions = `-- name: GetTransactions :many
WITH MultiItemSales AS (
    SELECT transaction_id 
    FROM transaction_items 
    GROUP BY transaction_id 
    HAVING COUNT(item_id) > 1
)
SELECT t.transaction_id, t.transaction_date, ti.item_id, ti.quantity 
FROM transactions t 
JOIN transaction_items ti ON t.transaction_id = ti.transaction_id
`

type GetTransactionsRow struct {
	TransactionID   int32
	TransactionDate time.Time
	ItemID          int32
	Quantity        int32
}

func (q *Queries) GetTransactions(ctx context.Context) ([]GetTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsRow
	for rows.Next() {
		var i GetTransactionsRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.TransactionDate,
			&i.ItemID,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
