// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_trans_by_id.sql

package database

import (
	"context"
	"time"
)

const getTransById = `-- name: GetTransById :many
WITH MultiItemSales AS (
    SELECT transaction_id 
    FROM transaction_items 
    GROUP BY transaction_id 
    HAVING COUNT(item_id) > 1
)
SELECT t.transaction_id, t.transaction_date, ti.item_id, ti.quantity 
FROM transactions t 
JOIN transaction_items ti ON t.transaction_id = ti.transaction_id 
WHERE t.transaction_id = $1
`

type GetTransByIdRow struct {
	TransactionID   int32
	TransactionDate time.Time
	ItemID          int32
	Quantity        int32
}

func (q *Queries) GetTransById(ctx context.Context, transactionID int32) ([]GetTransByIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransById, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransByIdRow
	for rows.Next() {
		var i GetTransByIdRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.TransactionDate,
			&i.ItemID,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
