// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_user_by_username.sql

package database

import (
	"context"
)

const getUserByUserName = `-- name: GetUserByUserName :one
SELECT id, created_at, updated_at, access_level, first_name, last_name, password_hash, active, user_name
FROM users
WHERE user_name = $1
`

func (q *Queries) GetUserByUserName(ctx context.Context, userName string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUserName, userName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccessLevel,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.Active,
		&i.UserName,
	)
	return i, err
}
