// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_items.sql

package database

import (
	"context"
)

const getItems = `-- name: GetItems :many
SELECT upc, created_at, updated_at, item_name, item_desc, item_retail, item_cost, item_picture
FROM items
`

func (q *Queries) GetItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.Upc,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemName,
			&i.ItemDesc,
			&i.ItemRetail,
			&i.ItemCost,
			&i.ItemPicture,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
