// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_item_by_upc.sql

package database

import (
	"context"
)

const getItemByUpc = `-- name: GetItemByUpc :one
SELECT upc, created_at, updated_at, item_name, item_desc, item_retail, item_cost, item_picture
FROM items
WHERE upc = $1
`

func (q *Queries) GetItemByUpc(ctx context.Context, upc string) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByUpc, upc)
	var i Item
	err := row.Scan(
		&i.Upc,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ItemName,
		&i.ItemDesc,
		&i.ItemRetail,
		&i.ItemCost,
		&i.ItemPicture,
	)
	return i, err
}
