// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_item_by_id.sql

package database

import (
	"context"
)

const getItemById = `-- name: GetItemById :one
SELECT upc, created_at, updated_at, item_name, item_desc, item_retail, item_cost, item_picture, item_id
FROM items
WHERE item_id = $1
`

func (q *Queries) GetItemById(ctx context.Context, itemID int32) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemById, itemID)
	var i Item
	err := row.Scan(
		&i.Upc,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ItemName,
		&i.ItemDesc,
		&i.ItemRetail,
		&i.ItemCost,
		&i.ItemPicture,
		&i.ItemID,
	)
	return i, err
}
