// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Item struct {
	Upc         string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ItemName    string
	ItemDesc    sql.NullString
	ItemRetail  float64
	ItemCost    float64
	ItemPicture sql.NullString
	ItemID      int32
}

type Transaction struct {
	TransactionID   int32
	CustomerID      int32
	TransactionDate time.Time
}

type TransactionItem struct {
	ItemID        int32
	TransactionID int32
	Quantity      int32
	Price         float64
}

type User struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	AccessLevel  string
	FirstName    string
	LastName     string
	PasswordHash string
	Active       bool
	UserName     string
}
